// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_PsFV7W7HXU2KK8G_Jugw4qaHheR7M9E',
    appId: '1:9433507759:web:703355012ca163013ff15a',
    messagingSenderId: '9433507759',
    projectId: 'one-note-8d0da',
    authDomain: 'one-note-8d0da.firebaseapp.com',
    storageBucket: 'one-note-8d0da.appspot.com',
    measurementId: 'G-XMN95ZB0N1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtwGXPma7cbewQwaIf2eor6-YvLDKXSH0',
    appId: '1:9433507759:ios:96507763ea1c9e593ff15a',
    messagingSenderId: '9433507759',
    projectId: 'one-note-8d0da',
    storageBucket: 'one-note-8d0da.appspot.com',
    iosBundleId: 'com.example.oneNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_PsFV7W7HXU2KK8G_Jugw4qaHheR7M9E',
    appId: '1:9433507759:web:fca5275bf31722693ff15a',
    messagingSenderId: '9433507759',
    projectId: 'one-note-8d0da',
    authDomain: 'one-note-8d0da.firebaseapp.com',
    storageBucket: 'one-note-8d0da.appspot.com',
    measurementId: 'G-ZM085WSYZR',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtwGXPma7cbewQwaIf2eor6-YvLDKXSH0',
    appId: '1:9433507759:ios:96507763ea1c9e593ff15a',
    messagingSenderId: '9433507759',
    projectId: 'one-note-8d0da',
    storageBucket: 'one-note-8d0da.appspot.com',
    iosBundleId: 'com.example.oneNote',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZkp7FITlMk4sizIuUG18yGcFFx7bYUMU',
    appId: '1:9433507759:android:251f3cabde07bec13ff15a',
    messagingSenderId: '9433507759',
    projectId: 'one-note-8d0da',
    storageBucket: 'one-note-8d0da.appspot.com',
  );

}